### ISSUE TITLE
Server can't handle too big files because of grpc limits: StatusCode.RESOURCE_EXHAUSTED, grpc: trying to send message larger than max

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/server#57]
Code & repo to reproduce
```
# repo to reproduce
git clone https://github.com/svn2github/icu4j/ --depth 1
# bblfsh client call to reproduce error
root@science-3:~/tmp# PYTHONPATH=/media/root/storage/egor/ast2vec_rsync:/media/root/storage/egor/ast2vec_rsync/src/bblfsh GRPC_ARG_MAX_SEND_MESSAGE_LENGTH=-1 python3 -m bblfsh --disable-bblfsh-autorun -e 172.17.0.1:9432 -f icu4j/main/tests/core/src/com/ibm/icu/dev/test/bigdec/DiagBigDecimalTest.java
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/__main__.py", line 34, in <module>
    sys.exit(main())
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/__main__.py", line 30, in main
    print(client.parse_uast(args.file, args.language))
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/client.py", line 62, in parse_uast
    response = self._stub.ParseUAST(request, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.RESOURCE_EXHAUSTED, grpc: trying to send message larger than max (4315530 vs. 4194304))>
```

**Comment by juanjux** [comment]
We should be able to change it with:

https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize

We also should should test the performance implications of changing the size. Maybe we could dynamically change the size of the message as part of the protocol?

**Comment by juanjux** [comment]
From @EgorBu on slack:

```
size of file to reproduce error:
root@science-3:~/tmp# ls -sh icu4j/main/tests/core/src/com/ibm/icu/dev/test/bigdec/DiagBigDecimalTest.java
424K icu4j/main/tests/core/src/com/ibm/icu/dev/test/bigdec/DiagBigDecimalTest.java
```

**Comment by abeaumont** [comment]
@juanjux I don't think that can be part of the protocol since it's a server configuration parameter, which has to be set before receiving protocol messages.
I'll add a CLI option to be able to override that value.

**Comment by juanjux** [comment]
It could be a previous message type, a control message, this could be interesting if increasing the max size destroys performance for the average request for example, but it the performance is unaffected or only slightly worse i wouldn't care with the hassle of doing this. Also, maybe the server can't change these settings dynamically once its running.

**Comment by bzz** [comment]
FYI - I was not hit by this issue using a sequential, single thread Golang client. 
AFAIK @egor uses Python one in a heavily parallel workflow.

**Comment by abeaumont** [comment]
@EgorBu can you make that `Java` file accessible somewhere or provide a link to it?
