### ISSUE TITLE
corrupted response from server

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/server#59]
reproducible for https://github.com/spring/svn-spring-archive
specific file: https://github.com/spring/svn-spring-archive/blob/master/Lobby/TASServer/TASServer.java
```^[[1;31mERROR^[[0m:root:^[[0mException deserializing message!^[[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grpc/_common.py", line 129, in _transform
    return transformer(message)
google.protobuf.message.DecodeError: Error parsing message
^[[1;36mINFO^[[0m:repos2coocc:^[[0mhttps://github.com/shaunduncan/helga.git pending tasks: 43^[[0m
^[[1;36mINFO^[[0m:repos2coocc:^[[0mhttps://github.com/ups-nlp/nlp425.git pending tasks: 17^[[0m
^[[1;31mERROR^[[0m:repos2coocc:^[[0mError while processing ('/tmp/repo2nbow-6lu1go2q/TASServer/TASServer.java', 'Java').^[[0m
Traceback (most recent call last):
  File "/media/root/storage/egor/ast2vec_rsync/ast2vec/repo2base.py", line 97, in thread_loop
    filename, language=language, timeout=self._timeout)
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/client.py", line 62, in parse_uast
    response = self._stub.ParseUAST(request, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Exception deserializing response!)>
```

code to reproduce:
```
python3 -m bblfsh -e 0.0.0.0:9432 -f TASServer.java --disable-bblfsh-autorun
ERROR:root:Exception deserializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grpc/_common.py", line 129, in _transform
    return transformer(message)
google.protobuf.message.DecodeError: Error parsing message
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/__main__.py", line 34, in <module>
    sys.exit(main())
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/__main__.py", line 30, in main
    print(client.parse_uast(args.file, args.language))
  File "/media/root/storage/egor/ast2vec_rsync/src/bblfsh/bblfsh/client.py", line 62, in parse_uast
    response = self._stub.ParseUAST(request, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Exception deserializing response!)>
```

**Comment by abeaumont** [comment]
@EgorBu that specific file doesn't exist. Could you fix the link please?

**Comment by EgorBu** [comment]
@abeaumont , thanks, link is fixed

**Comment by abeaumont** [comment]
I cannot reproduce it with `bblfsh client`, so it may be python specific

**Comment by abeaumont** [comment]
I can reproduce it with `client-python`

```
> python3 -m bblfsh -f TASServer.java 
ERROR:root:Exception deserializing message!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/grpc/_common.py", line 129, in _transform
    return transformer(message)
google.protobuf.message.DecodeError: Error parsing message
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abeaumont/src-d/ast2vec/src/bblfsh/bblfsh/__main__.py", line 34, in <module>
    sys.exit(main())
  File "/home/abeaumont/src-d/ast2vec/src/bblfsh/bblfsh/__main__.py", line 30, in main
    print(client.parse_uast(args.file, args.language))
  File "/home/abeaumont/src-d/ast2vec/src/bblfsh/bblfsh/client.py", line 53, in parse_uast
    response = self._stub.ParseUAST(request)
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Exception deserializing response!)>
```

**Comment by abeaumont** [comment]
It seems a tree depth problem. I've been able to generate some minimal samples that reproduces the error in both `python` and `java`:
* `python`: https://gist.github.com/abeaumont/57e4b5bbd205d7613aca4b2755cb2fbc
* `java`: https://gist.github.com/abeaumont/df5d6e41b559e8fd2aed40a1895d4972

So it's more likely a bug with `grpc`

**Comment by abeaumont** [comment]
It seems like a python protobuf problem, I've been able to reproduce the decoding just trying to deserialize the serialized pb:

```python
#!/usr/bin/env python
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__),
                                "github/com/bblfsh/sdk/protocol"))
from bblfsh.github.com.bblfsh.sdk.protocol.generated_pb2 import ParseUASTResponse

print(ParseUASTResponse.FromString(open(sys.argv[1], 'rb').read()))
```

```
> python a.py ~/t.py.pb
Traceback (most recent call last):
  File "a.py", line 9, in <module>
    print(ParseUASTResponse.FromString(open(sys.argv[1], 'rb').read()))
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by abeaumont** [comment]
Using protobuf directly from `git` seems to work:
```
$ git clone https://github.com/google/protobuf.git
$ cd protobuf/python
$ python setup.py build
$ PYTHONPATH=~/protobuf/python/build/lib/ python ~/a.py ~/t.py.pb
uast {
  internal_type: "If"
  properties {
    key: "internalRole"
    value: "body"
```

@EgorBu you may want to try that workaround. I don't think we can anything else on our side.

**Comment by zurk** [comment]
Yes, It helps me.
I found that the problem appears with protobuf `v3.3.0` python package.
If you will get `v3.3.2`, it works fine. But it is not in PyPl now, you need to install it from git as @abeaumont said [here](https://github.com/bblfsh/server/issues/59#issuecomment-314503776).

But It is also `protoc` file should be somewhere in your PATH.
You can build it from source or get from `v3.3.0` release, as I do, it works.
Now I have this fix-script (run under root):
```bash
# Install normal protobuf
# Make sure you grab the latest version
curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip

# Unzip
unzip protoc-3.3.0-linux-x86_64.zip -d protoc3

# Move protoc to /usr/local/bin/
mv protoc3/bin/* /usr/local/bin/

# Move protoc3/include to /usr/local/include/
mv protoc3/include/* /usr/local/include/

# Remove protoc3 folder
rm -rf protoc3

# Get latest protobuf, now it is v3.3.2
git clone https://github.com/google/protobuf

# And install python wrapper
cd protobuf/python
python3 setup.py build
pip3 install .

cd ../../
rm -rf protobuf
```
